/**
 * The synthetic community index.
 *
 * SYNTHETIC. Every community below is invented. Real IRL communities are real
 * organisations run by real people, and attaching invented reach, pricing, and
 * conversion numbers to their names would misrepresent them. Do not replace
 * these with real names.
 *
 * What is NOT invented is the calibration:
 *   - The six categories mirror how this kind of index is actually organised.
 *   - The mix is weighted toward run clubs, the deepest category by far.
 *   - Blended network rates land near 93% check-in / 48% click / 11% convert.
 *
 * `engine.test.ts` asserts all of the above. If you add rows, keep it passing.
 * An engine tuned to the wrong world prices every campaign wrong.
 */

import type { Community } from '../lib/scoring/types';

export const COMMUNITY_INDEX: readonly Community[] = [
  {
    id: "sunrise-mile",
    name: "Sunrise Mile Club",
    city: "New York",
    category: "run club",
    interests: ["running", "fitness", "morning", "apparel", "coffee", "wellness"],
    attendance: 180,
    eventsPerMonth: 4,
    ageRange: "22-32",
    checkInRate: 0.94,
    ctr: 0.5,
    cvr: 0.11,
    feeCents: 340000,
    brandSafety: 0.97,
    waitlistRatio: 1.4,
    formats: ["sampling", "co-host", "product integration"],
    pastCategories: ["apparel", "beverage"],
  },
  {
    id: "boroughs-track",
    name: "Boroughs Track Club",
    city: "Brooklyn",
    category: "run club",
    interests: ["running", "track", "fitness", "streetwear", "community"],
    attendance: 240,
    eventsPerMonth: 4,
    ageRange: "21-31",
    checkInRate: 0.88,
    ctr: 0.44,
    cvr: 0.09,
    feeCents: 420000,
    brandSafety: 0.94,
    waitlistRatio: 2.2,
    formats: ["sampling", "venue takeover", "co-host"],
    pastCategories: ["apparel", "beverage"],
  },
  {
    id: "lakefront-pace",
    name: "Lakefront Pace",
    city: "Chicago",
    category: "run club",
    interests: ["running", "fitness", "morning", "gear", "outdoors"],
    attendance: 210,
    eventsPerMonth: 4,
    ageRange: "23-35",
    checkInRate: 0.92,
    ctr: 0.47,
    cvr: 0.1,
    feeCents: 380000,
    brandSafety: 0.96,
    waitlistRatio: 1.8,
    formats: ["sampling", "co-host", "product integration"],
    pastCategories: ["apparel", "wellness"],
  },
  {
    id: "taco-tuesday-run",
    name: "Taco Tuesday Runners",
    city: "Austin",
    category: "run club",
    interests: ["running", "food", "fitness", "beverage", "community"],
    attendance: 150,
    eventsPerMonth: 4,
    ageRange: "22-33",
    checkInRate: 0.95,
    ctr: 0.52,
    cvr: 0.12,
    feeCents: 290000,
    brandSafety: 0.95,
    waitlistRatio: 2.4,
    formats: ["sampling", "co-host"],
    pastCategories: ["beverage", "apparel"],
  },
  {
    id: "sunset-strides",
    name: "Sunset Strides LA",
    city: "Los Angeles",
    category: "run club",
    interests: ["running", "fitness", "wellness", "apparel", "recovery"],
    attendance: 175,
    eventsPerMonth: 4,
    ageRange: "24-34",
    checkInRate: 0.9,
    ctr: 0.46,
    cvr: 0.1,
    feeCents: 330000,
    brandSafety: 0.96,
    waitlistRatio: 1.6,
    formats: ["sampling", "product integration", "co-host"],
    pastCategories: ["apparel", "wellness"],
  },
  {
    id: "bridge-runners-atl",
    name: "Bridge Runners ATL",
    city: "Atlanta",
    category: "run club",
    interests: ["running", "fitness", "music", "streetwear", "community"],
    attendance: 130,
    eventsPerMonth: 4,
    ageRange: "21-32",
    checkInRate: 0.91,
    ctr: 0.5,
    cvr: 0.12,
    feeCents: 240000,
    brandSafety: 0.95,
    waitlistRatio: 1.5,
    formats: ["sampling", "co-host"],
    pastCategories: ["apparel", "beverage"],
  },
  {
    id: "riverside-run",
    name: "Riverside Run Society",
    city: "Philadelphia",
    category: "run club",
    interests: ["running", "fitness", "morning", "coffee", "gear"],
    attendance: 120,
    eventsPerMonth: 4,
    ageRange: "25-36",
    checkInRate: 0.96,
    ctr: 0.5,
    cvr: 0.11,
    feeCents: 220000,
    brandSafety: 0.98,
    waitlistRatio: 1.9,
    formats: ["sampling", "co-host", "product integration"],
    pastCategories: ["beverage", "apparel"],
  },
  {
    id: "dawn-patrol-run",
    name: "Dawn Patrol Run",
    city: "San Diego",
    category: "run club",
    interests: ["running", "outdoors", "morning", "surf", "gear"],
    attendance: 90,
    eventsPerMonth: 8,
    ageRange: "20-34",
    checkInRate: 0.89,
    ctr: 0.45,
    cvr: 0.1,
    feeCents: 210000,
    brandSafety: 0.96,
    waitlistRatio: 1.3,
    formats: ["sampling", "co-host"],
    pastCategories: ["outdoor", "apparel"],
  },
  {
    id: "motor-city-miles",
    name: "Motor City Miles",
    city: "Detroit",
    category: "run club",
    interests: ["running", "fitness", "music", "community", "morning"],
    attendance: 95,
    eventsPerMonth: 4,
    ageRange: "22-34",
    checkInRate: 0.93,
    ctr: 0.51,
    cvr: 0.12,
    feeCents: 180000,
    brandSafety: 0.96,
    waitlistRatio: 1.7,
    formats: ["sampling", "co-host"],
    pastCategories: ["apparel", "beverage"],
  },
  {
    id: "slow-loop",
    name: "Slow Loop Walk Club",
    city: "New York",
    category: "walking club",
    interests: ["walking", "wellness", "women", "morning", "coffee"],
    attendance: 260,
    eventsPerMonth: 4,
    ageRange: "23-33",
    checkInRate: 0.9,
    ctr: 0.48,
    cvr: 0.1,
    feeCents: 390000,
    brandSafety: 0.98,
    waitlistRatio: 2.6,
    formats: ["sampling", "co-host", "product integration"],
    pastCategories: ["beauty", "beverage", "wellness"],
  },
  {
    id: "sunday-steps",
    name: "Sunday Steps Seattle",
    city: "Seattle",
    category: "walking club",
    interests: ["walking", "outdoors", "wellness", "slow", "coffee"],
    attendance: 140,
    eventsPerMonth: 4,
    ageRange: "26-40",
    checkInRate: 0.95,
    ctr: 0.49,
    cvr: 0.12,
    feeCents: 210000,
    brandSafety: 0.99,
    waitlistRatio: 1.5,
    formats: ["sampling", "co-host"],
    pastCategories: ["wellness", "beverage"],
  },
  {
    id: "harbor-walkers",
    name: "Harbor Walkers",
    city: "Boston",
    category: "walking club",
    interests: ["walking", "outdoors", "morning", "wellness", "books"],
    attendance: 110,
    eventsPerMonth: 4,
    ageRange: "28-44",
    checkInRate: 0.97,
    ctr: 0.46,
    cvr: 0.11,
    feeCents: 170000,
    brandSafety: 0.99,
    waitlistRatio: 1.4,
    formats: ["sampling", "co-host", "product integration"],
    pastCategories: ["wellness", "home"],
  },
  {
    id: "sunset-stroll-mia",
    name: "Sunset Stroll Miami",
    city: "Miami",
    category: "walking club",
    interests: ["walking", "wellness", "fashion", "beauty", "community"],
    attendance: 190,
    eventsPerMonth: 2,
    ageRange: "24-38",
    checkInRate: 0.87,
    ctr: 0.43,
    cvr: 0.1,
    feeCents: 280000,
    brandSafety: 0.95,
    waitlistRatio: 1.6,
    formats: ["sampling", "venue takeover"],
    pastCategories: ["beauty", "beverage"],
  },
  {
    id: "trailhead-walkers",
    name: "Trailhead Walkers",
    city: "Denver",
    category: "walking club",
    interests: ["walking", "hiking", "outdoors", "gear", "sustainability"],
    attendance: 100,
    eventsPerMonth: 4,
    ageRange: "27-45",
    checkInRate: 0.94,
    ctr: 0.47,
    cvr: 0.12,
    feeCents: 160000,
    brandSafety: 0.99,
    waitlistRatio: 1.2,
    formats: ["sampling", "co-host", "product integration"],
    pastCategories: ["outdoor", "wellness"],
  },
  {
    id: "long-table",
    name: "The Long Table",
    city: "Brooklyn",
    category: "social club",
    interests: ["food", "chefs", "hosting", "wine", "design"],
    attendance: 40,
    eventsPerMonth: 2,
    ageRange: "26-38",
    checkInRate: 0.97,
    ctr: 0.61,
    cvr: 0.19,
    feeCents: 520000,
    brandSafety: 0.98,
    waitlistRatio: 3.1,
    formats: ["co-host", "product integration", "venue takeover"],
    pastCategories: ["beverage", "home"],
  },
  {
    id: "third-space-chess",
    name: "Third Space Chess",
    city: "New York",
    category: "social club",
    interests: ["chess", "strategy", "coffee", "books", "community"],
    attendance: 90,
    eventsPerMonth: 4,
    ageRange: "19-30",
    checkInRate: 0.95,
    ctr: 0.5,
    cvr: 0.11,
    feeCents: 230000,
    brandSafety: 0.99,
    waitlistRatio: 1.1,
    formats: ["sampling", "co-host"],
    pastCategories: ["beverage", "tech"],
  },
  {
    id: "rooftop-ceramics",
    name: "Rooftop Ceramics",
    city: "Brooklyn",
    category: "social club",
    interests: ["ceramics", "craft", "slow", "design", "hands-on"],
    attendance: 35,
    eventsPerMonth: 3,
    ageRange: "25-37",
    checkInRate: 0.98,
    ctr: 0.64,
    cvr: 0.21,
    feeCents: 290000,
    brandSafety: 0.99,
    waitlistRatio: 4.2,
    formats: ["co-host", "product integration"],
    pastCategories: ["home", "beauty"],
  },
  {
    id: "sober-social",
    name: "Sober Social",
    city: "New York",
    category: "social club",
    interests: ["sober", "wellness", "nightlife", "music", "community"],
    attendance: 220,
    eventsPerMonth: 2,
    ageRange: "23-34",
    checkInRate: 0.89,
    ctr: 0.45,
    cvr: 0.1,
    feeCents: 360000,
    brandSafety: 0.99,
    waitlistRatio: 2.4,
    formats: ["sampling", "co-host", "venue takeover"],
    pastCategories: ["beverage", "wellness"],
  },
  {
    id: "stitch-social",
    name: "Stitch Social",
    city: "Brooklyn",
    category: "girl group",
    interests: ["sewing", "craft", "slow", "fashion", "women", "hands-on"],
    attendance: 45,
    eventsPerMonth: 4,
    ageRange: "23-36",
    checkInRate: 0.96,
    ctr: 0.6,
    cvr: 0.18,
    feeCents: 190000,
    brandSafety: 0.99,
    waitlistRatio: 3.4,
    formats: ["co-host", "product integration"],
    pastCategories: ["fashion", "home"],
  },
  {
    id: "founders-friends",
    name: "Founders & Friends",
    city: "New York",
    category: "girl group",
    interests: ["startups", "networking", "business", "women", "community"],
    attendance: 130,
    eventsPerMonth: 2,
    ageRange: "24-36",
    checkInRate: 0.93,
    ctr: 0.54,
    cvr: 0.15,
    feeCents: 370000,
    brandSafety: 0.97,
    waitlistRatio: 2.9,
    formats: ["co-host", "sampling", "product integration"],
    pastCategories: ["tech", "finance", "beauty"],
  },
  {
    id: "pilates-pastries",
    name: "Pilates & Pastries",
    city: "Los Angeles",
    category: "girl group",
    interests: ["pilates", "wellness", "food", "beauty", "women"],
    attendance: 85,
    eventsPerMonth: 4,
    ageRange: "23-35",
    checkInRate: 0.95,
    ctr: 0.57,
    cvr: 0.16,
    feeCents: 260000,
    brandSafety: 0.98,
    waitlistRatio: 2.7,
    formats: ["sampling", "co-host", "product integration"],
    pastCategories: ["beauty", "wellness", "beverage"],
  },
  {
    id: "silent-book",
    name: "Silent Book Hour",
    city: "Chicago",
    category: "book club",
    interests: ["books", "quiet", "solo", "coffee", "wellness"],
    attendance: 70,
    eventsPerMonth: 4,
    ageRange: "24-36",
    checkInRate: 0.96,
    ctr: 0.52,
    cvr: 0.14,
    feeCents: 150000,
    brandSafety: 0.99,
    waitlistRatio: 2.7,
    formats: ["sampling", "co-host"],
    pastCategories: ["beverage", "home"],
  },
  {
    id: "backlist-society",
    name: "Backlist Society",
    city: "Washington",
    category: "book club",
    interests: ["books", "ideas", "literary", "wine", "design"],
    attendance: 60,
    eventsPerMonth: 2,
    ageRange: "26-42",
    checkInRate: 0.94,
    ctr: 0.55,
    cvr: 0.15,
    feeCents: 140000,
    brandSafety: 0.98,
    waitlistRatio: 1.8,
    formats: ["co-host", "product integration"],
    pastCategories: ["media", "beverage"],
  },
  {
    id: "stroller-squad",
    name: "Stroller Squad",
    city: "Houston",
    category: "mom group",
    interests: ["parenting", "walking", "wellness", "home", "morning"],
    attendance: 75,
    eventsPerMonth: 4,
    ageRange: "28-40",
    checkInRate: 0.92,
    ctr: 0.58,
    cvr: 0.17,
    feeCents: 180000,
    brandSafety: 0.99,
    waitlistRatio: 2.1,
    formats: ["sampling", "co-host", "product integration"],
    pastCategories: ["home", "wellness", "beauty"],
  },
];
